### ISSUE TITLE
Jellybeans different colors (Vim vs Gvim)

### ISSUE THREAD

**Issue by 8carlosf** [vim-airline/vim-airline-themes#24]
After recent updates (weeks ago, not sure when), colors don't match, but only in the airline, the syntax is fine. This also happens with base16 (look like a global problem). This problem happens in Normal, Insert or Visual Mode colors.

Vim (termite [same in urxvt], vim-plug up-to-date)
![1457570199](https://cloud.githubusercontent.com/assets/3144322/13655581/671f2bfa-e658-11e5-87ce-32821d7d0745.png)

Gvim
![1457570202](https://cloud.githubusercontent.com/assets/3144322/13655582/6958e604-e658-11e5-8676-2089fd40ff35.png)

Thanks for the awesome work, airline rulez!

**Comment by betaveros** [comment]
+1 to this. After bisecting, I think the refactoring commit https://github.com/vim-airline/vim-airline-themes/commit/848cc7c1f76f950ea7b0cd72c8303a1d73bcf15b changed a lot of the theme...

**Comment by 8carlosf** [comment]
I tried other themes and they are off too. I'm not sure it is a theme problem, or a problem with the plugin itself. So I left a issue report in both :/

**Comment by betaveros** [comment]
Eh, since I fortunately had a different computer where I hadn't updated all my bundles, I was able to figure out how the theme code worked and copy over all the old colors (but while ruining most of the refactoring benefits of keeping colors in the same place), and my jellybeans looks exactly as I remembered it again:

```diff
diff --git a/autoload/airline/themes/jellybeans.vim b/autoload/airline/themes/jellybeans.vim
index 6d2c2b1..7c96057 100644
--- a/autoload/airline/themes/jellybeans.vim
+++ b/autoload/airline/themes/jellybeans.vim
@@ -38,35 +38,38 @@ let s:ctermWhite = "15"
 
 let g:airline#themes#jellybeans#palette = {}
 
+let s:G2 = [ "#A0A8B0", "#384048", "145", "236" ]
+let s:G3 = [ "#606060", "#151515", "240", "16" ]
+let s:modified = {
+        \ 'airline_c': [ '#ffb964', '', 215, '', '' ]
+        \ }
+
 " Normal mode
-let s:N1 = [ s:gui07 , s:gui0D , s:cterm07 , s:cterm0D  ]
-let s:N2 = [ s:gui04 , s:gui01 , s:cterm04 , s:cterm01  ]
-let s:N3 = [ s:gui02 , s:gui00 , s:cterm02 , s:cterm00  ]
-let g:airline#themes#jellybeans#palette.normal = airline#themes#generate_color_map(s:N1, s:N2, s:N3)
+let s:N1 = [ "#DEEBFE", "#345FA8", "195", "25" ]
+let g:airline#themes#jellybeans#palette.normal = airline#themes#generate_color_map(s:N1, s:G2, s:G3)
+let g:airline#themes#jellybeans#palette.normal_modified = s:modified
 
 " Insert mode
-let s:I1 = [ s:guiWhite , s:gui0B , s:ctermWhite , s:cterm0B  ]
-let s:I2 = [ s:gui04 , s:gui01 , s:cterm04 , s:cterm01  ]
-let s:I3 = [ s:guiWhite , s:gui01 , s:ctermWhite , s:cterm00  ]
-let g:airline#themes#jellybeans#palette.insert = airline#themes#generate_color_map(s:I1, s:I2, s:I3)
+let s:I1 = [ "#D2EBBE", "#437019", "193", "22" ]
+let g:airline#themes#jellybeans#palette.insert = airline#themes#generate_color_map(s:I1, s:G2, s:G3)
+let g:airline#themes#jellybeans#palette.insert_modified = s:modified
 
 " Visual mode
-let s:V1 = [ s:guiWhite , s:gui08 , s:ctermWhite , s:cterm08 ]
-let s:V2 = [ s:gui04 , s:gui01 , s:cterm04 , s:cterm01  ]
-let s:V3 = [ s:guiWhite , s:gui01 , s:ctermWhite , s:cterm00  ]
-let g:airline#themes#jellybeans#palette.visual = airline#themes#generate_color_map(s:V1, s:V2, s:V3)
+let s:V1 = [ "#f0f0f0", "#700009", "254", "52" ]
+let g:airline#themes#jellybeans#palette.visual = airline#themes#generate_color_map(s:V1, s:G2, s:G3)
+let g:airline#themes#jellybeans#palette.visual_modified = s:modified
 
 " Replace mode
-let s:R1 = [ s:gui08 , s:gui01 , s:cterm08, s:cterm00 ]
-let s:R2 = [ s:gui02 , s:gui01 , s:cterm03 , s:cterm01  ]
-let s:R3 = [ s:guiWhite , s:gui01 , s:ctermWhite , s:cterm00  ]
-let g:airline#themes#jellybeans#palette.replace = airline#themes#generate_color_map(s:R1, s:R2, s:R3)
+let s:R1 = [ "#f0a0c0", "#302028", "217", "16" ]
+let g:airline#themes#jellybeans#palette.replace = airline#themes#generate_color_map(s:R1, s:G2, s:G3)
+let g:airline#themes#jellybeans#palette.replace_modified = s:modified
 
 " Inactive mode
 let s:IN1 = [ s:gui00 , s:gui01 , s:cterm00 , s:cterm01 ]
 let s:IN2 = [ s:gui02 , s:gui00 , s:cterm02 , s:cterm00 ]
 let s:IN3 = [ s:gui02 , s:gui00 , s:cterm02 , s:cterm00 ]
 let g:airline#themes#jellybeans#palette.inactive = airline#themes#generate_color_map(s:IN1, s:IN2, s:IN3)
+let g:airline#themes#jellybeans#palette.inactive_modified = s:modified
 
 " CtrlP
 if !get(g:, 'loaded_ctrlp', 0)
```

I think the general theme infrastructure is fine, but I don't know why this difference occurred, how much of it is deliberate, how other themes were affected, or what other changes might have happened in the meantime.

**Comment by chrisbra** [comment]
Does your patch also fix #6? If so, please make a new PR then.

**Comment by betaveros** [comment]
AFAICT, #6 was already fixed; I never saw a red bar.

**Comment by 8carlosf** [comment]
same here, never saw a red bar.. I'm on the latest commit in both vim-airline and vim-airline-themes, and this problem is still there

**Comment by chrisbra** [comment]
Yeah, afaict it was fact by 848cc7c and I am wondering, whether your fix reverts that one.

**Comment by betaveros** [comment]
Oh, I understand. I think the colors here are definitely different from the colors in that commit, but I don't think this fix reintroduces a red bar. I may make a PR after cleaning it up more, if that's what y'all want?

**Comment by mhartington** [comment]
Just chiming in on this. The commit uses the same colors that jellybeans uses and in turn uses the same colors that the original used. I can take look at why the colors are off

**Comment by betaveros** [comment]
After looking at jellybeans.vim, I suspect you are extracting cterm colors from when `s:low_color = 1`.

When this is true, `DbgCurrent` (which the airline theme originally copied for the normal first section of the airline) is highlighted as `ctermfg=15 ctermbg=4`; but when it's false, `DbgCurrent` is highlighted as `ctermfg=195 ctermbg=25`, which is the appearance I'm used to and IMO much prettier.

**Comment by betaveros** [comment]
Although, this doesn't explain why some GUI colors are still different (and they are --- for example, noticeably, the orange accent when the file you're editing has been modified but not written is gone.)

**Comment by murkey** [comment]
I'm not 100% sure if this is the same issue, but this is what I'm seeing with the jellybeans theme:
![](http://i.imgur.com/I01y2KS.png)

The blue looks like standard 16-color blue. powerlineish worked as expected. `$TERM` is `xterm-256color`. Using iTerm... [Here's my .vimrc](https://gist.github.com/murkey/dec16ce0abdafcd507814d633c742f03), let me know if I can be helpful.

**Comment by betaveros** [comment]
Oh oops I forgot about this issue and what I had done. I'll still PR what I have, I guess, to see which one people prefer; you should probably just ignore it if @8carlosf 's is satisfactory.

**Comment by chrisbra** [comment]
should be fixed now.
